##set server port
server:
  port: 8080

spring:
  ##set app name
  application:
    name: feign-server
    ##use nacos discovery
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848